### ISSUE TITLE
Unidad de medida inválida

### ISSUE THREAD

**Issue by beniju** [TIPS-SA/facturacionelectronicapy-xmlgen#16]
En el archivo: **ConstanteService**, la representación de la unidad de medida con código 79 está equivocado.
`{ codigo: 79, representacion: 'kg/m² ', descripcion: 'Kilogramos s/ metro cuadrado' },`

![image](https://github.com/TIPS-SA/facturacionelectronicapy-xmlgen/assets/16580176/6ff9b055-9279-4070-83f1-857420ae54df)

debe ser:
`{ codigo: 79, representacion: 'kg/m2 ', descripcion: 'Kilogramos s/ metro cuadrado' },`

![image](https://github.com/TIPS-SA/facturacionelectronicapy-xmlgen/assets/16580176/8d371a3c-911d-442f-8a2d-eafc4caa18ad)

Obs.: en el manual técnico v150 está expresado de la misma forma como en la constante, pero en el XSD de la SIFEN está diferente.

**Comment by marcosjara** [comment]
Gracias por tu aporte!

**Comment by beniju** [comment]
A ustedes por la librería!
